name: newsscraper
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: VectorVerse-Evolve-Inc/NewsScraper
  dockerfile_path: Dockerfile
  http_port: 8501
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: COHERE_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${COHERE_API_KEY}
  - key: NEWS_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${NEWS_API_KEY}
  - key: NEWS_DATA_HUB_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${NEWS_DATA_HUB_KEY}
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${OPENAI_API_KEY}
  - key: ELEVENLABS_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${ELEVENLABS_API_KEY}
  - key: SYNC_SO_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${SYNC_SO_API_KEY} 