version: '3'

services:
  agentic-content-transformer:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    restart: always
    environment:
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - SYNC_SO_API_KEY=${SYNC_SO_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEWS_DATA_HUB_KEY=${NEWS_DATA_HUB_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
    volumes:
      - app-data:/app/data
    networks:
      - app-network
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - agentic-content-transformer
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  app-data: 